print("Data Literacy Field Notes")
print("column : model")
print("example value : m4")
print ('inferred data type : string')
print ('This variable represents the model of the car')
print()
print('Data Structure Classification')
print('The dataset is structured because the information is organized into rows and columns.')
print()
print('Data Quality Question')
print('How was the price column data collected and validated? Prices change often especially for cars')